/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GiftVoucherAbi } from "./GiftVoucherAbi";

export { GiftVoucherAbi__factory } from "./factories/GiftVoucherAbi__factory";
